[tools]
node = "22"
go = "latest"
python = "3.12"

# Kubernetes
kubectl = "latest"
helm = "latest"
kustomize = "latest"
k9s = "latest"
stern = "latest"
terraform = "latest"

[settings]
idiomatic_version_file = true
legacy_version_file = true
trusted_config_paths = ["~/Desktop/kubecraft"]
